### ISSUE TITLE
Partition sizes intentional?

### ISSUE THREAD

**Issue by Schaka** [HybridELEC/hepacker#3]
Currently, partition sizes are too small to allow an update via CoreELEC.

I vaguely recall seeing somewhere that this is intentional to prevent it from being useable by Chinese resellers. 
I want to make sure if I adjust the sizes for myself and this is intentional, that I don't publish an easily abuseable image.

**Comment by 7Ji** [comment]
That was a point I insisted. However I decided to drop those limitations after seeing the images already abused in the current state. Heck, some sellers even hacked my app to erase all copyright infos and switch those to their dumb-ass texts, and they figured dirty ways to mod the image to implement their substituted CoreELEC system.

After one of the resellers reached  to me to ask if I can do modification for them -- of course I refused, I figured all these limitations are of no use. As long as you have an image published publicly these resellers would abuse them. So instead of some misguided users abused by them by purchasing their boxes and images, I decided to open them all so every one can enjoy their own image.

About the system partition size, you can set it by yourself after https://github.com/HybridELEC/hepacker/commit/a0c06038700042b869c8a1e131165c7e69bff933 . The previous behaviour is similar to `--system +2M`  with the current hepacker, that is, it would try its best to find the smallest system partition if possible. That was for two purposes: 1. to minimize the eMMC utilization so more data could be stored, this is especially useful for 8G eMMC boxes 2. to make  system upgrade impossible so system wouldn't be broken after an official update so CE/EE officials won't be bothered by users seeking for help form them, and these resellers won't be able to implement their modified CE/EE with different CE/EE image.

With the limitation removed you can freely decide the system partition side. You can still set a small system partition size if you want to achieve 1 to minimum eMMC utilization, but you don't need to achieve 2 any more, as that pretty much prevents nothing.

**Comment by Schaka** [comment]
That answers my question thoroughly, thank you for taking the time.
You've been immensely helpful. Is there a way I can send you a few bucks to buy you a beer? 

I didn't see anything on your GitHub profile.

**Comment by 7Ji** [comment]
A big warning though, while system upgrades would be possible if you set a large enough system partition, system would be broken after an update if you don't re-mod the startup script (at least `cfgload`), as the embedded CE/EE uses different startup scripts from the official one. Check `building/ce_system/cfgload` and `building/ce_system/config.ini` for examples.  You should be able to keep the system working if you back up them and restore them before and after update, though.

> You've been immensely helpful. Is there a way I can send you a few bucks to buy you a beer?
> I didn't see anything on your GitHub profile.

Thanks, I don't accept sponsorship as I do FOSS stuffs for interest and don't want the direction being partially determined by sponsors (even if people don't ask). I was once a member of team EmuELEC and I've seen how the project went from a hobby-first emulation project to a "sponsors want this port so let's add this port"-kind project, and I don't want that to happen for me. Also as I have a full-time job and live in China I strongly don't want to be "for-profit" (at least considered by big brother) or being related to any party. In short, doing all these solo without sponsorship ensures my freedom to do anything I want and I love that feeling. Starring the projects and follow me is enough.

**Comment by Schaka** [comment]
I think you're right. For friends and family that'll be too complicated. I'll keep the bigger partition so I can update my own devices but I'll disable updates and keep the partition as small as possible for anything I publish and the players I hand out. No way I want to deal with the support requests after the brick boot 😂
